# ============================================================
# Chatwoot SDR IA - Stack Docker Swarm
# ============================================================
# Stack completa e pronta para produção
#
# Uso:
#   1. Copie o arquivo .env.example para .env
#   2. Configure as variáveis no .env
#   3. Deploy: docker stack deploy -c chatwoot-sdr-ia.yml chatwoot
#
# Mantido por: eversonsantos-dev
# ============================================================

version: '3.8'

services:
  # ========================================
  # CHATWOOT APP (Rails Server)
  # ========================================
  app:
    image: eversonsantosdev/chatwoot-sdr-ia:latest
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    entrypoint: docker/entrypoints/rails.sh

    environment:
      # Rails
      - RAILS_ENV=production
      - NODE_ENV=production
      - INSTALLATION_ENV=docker
      - RAILS_LOG_TO_STDOUT=true
      - LOG_LEVEL=info

      # Database
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=${POSTGRES_DATABASE:-chatwoot_production}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

      # Redis
      - REDIS_URL=redis://redis:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}

      # Application
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - FRONTEND_URL=${FRONTEND_URL}
      - DEFAULT_LOCALE=${DEFAULT_LOCALE:-pt_BR}

      # Mailer
      - MAILER_SENDER_EMAIL=${MAILER_SENDER_EMAIL:-}
      - SMTP_ADDRESS=${SMTP_ADDRESS:-}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USERNAME=${SMTP_USERNAME:-}
      - SMTP_PASSWORD=${SMTP_PASSWORD:-}
      - SMTP_AUTHENTICATION=${SMTP_AUTHENTICATION:-plain}
      - SMTP_ENABLE_STARTTLS_AUTO=${SMTP_ENABLE_STARTTLS_AUTO:-true}

      # Storage (S3 ou local)
      - ACTIVE_STORAGE_SERVICE=${ACTIVE_STORAGE_SERVICE:-local}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME:-}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-}
      - AWS_REGION=${AWS_REGION:-}

      # Push Notifications (opcional)
      - VAPID_PUBLIC_KEY=${VAPID_PUBLIC_KEY:-}
      - VAPID_PRIVATE_KEY=${VAPID_PRIVATE_KEY:-}

      # Facebook/Instagram (opcional)
      - FB_VERIFY_TOKEN=${FB_VERIFY_TOKEN:-}
      - FB_APP_SECRET=${FB_APP_SECRET:-}
      - FB_APP_ID=${FB_APP_ID:-}
      - IG_VERIFY_TOKEN=${IG_VERIFY_TOKEN:-}

    volumes:
      - chatwoot_storage:/app/storage
      - chatwoot_public:/app/public

    networks:
      - chatwoot_network

    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.chatwoot.rule=Host(`${FRONTEND_URL_HOST:-chat.exemplo.com}`)"
        - "traefik.http.routers.chatwoot.entrypoints=websecure"
        - "traefik.http.routers.chatwoot.tls.certresolver=letsencrypt"
        - "traefik.http.services.chatwoot.loadbalancer.server.port=3000"

    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:3000/api || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

    depends_on:
      - postgres
      - redis

  # ========================================
  # CHATWOOT SIDEKIQ (Background Jobs)
  # ========================================
  sidekiq:
    image: eversonsantosdev/chatwoot-sdr-ia:latest
    command: bundle exec sidekiq -C config/sidekiq.yml

    environment:
      # Mesmas variáveis do app
      - RAILS_ENV=production
      - NODE_ENV=production
      - INSTALLATION_ENV=docker
      - RAILS_LOG_TO_STDOUT=true
      - LOG_LEVEL=info

      # Database
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=${POSTGRES_DATABASE:-chatwoot_production}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

      # Redis
      - REDIS_URL=redis://redis:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}

      # Application
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - FRONTEND_URL=${FRONTEND_URL}
      - DEFAULT_LOCALE=${DEFAULT_LOCALE:-pt_BR}

      # Mailer
      - MAILER_SENDER_EMAIL=${MAILER_SENDER_EMAIL:-}
      - SMTP_ADDRESS=${SMTP_ADDRESS:-}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USERNAME=${SMTP_USERNAME:-}
      - SMTP_PASSWORD=${SMTP_PASSWORD:-}
      - SMTP_AUTHENTICATION=${SMTP_AUTHENTICATION:-plain}
      - SMTP_ENABLE_STARTTLS_AUTO=${SMTP_ENABLE_STARTTLS_AUTO:-true}

      # Storage
      - ACTIVE_STORAGE_SERVICE=${ACTIVE_STORAGE_SERVICE:-local}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME:-}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-}
      - AWS_REGION=${AWS_REGION:-}

    volumes:
      - chatwoot_storage:/app/storage

    networks:
      - chatwoot_network

    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 256M

    depends_on:
      - postgres
      - redis

  # ========================================
  # POSTGRESQL (Database)
  # ========================================
  postgres:
    image: pgvector/pgvector:pg16

    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE:-chatwoot_production}
      - POSTGRES_USER=${POSTGRES_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - chatwoot_network

    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 256M

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USERNAME:-postgres} -d ${POSTGRES_DATABASE:-chatwoot_production}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # ========================================
  # REDIS (Cache & Queue)
  # ========================================
  redis:
    image: redis:7-alpine
    command: >
      sh -c "redis-server
      --appendonly yes
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
      ${REDIS_PASSWORD:+--requirepass $REDIS_PASSWORD}"

    volumes:
      - redis_data:/data

    networks:
      - chatwoot_network

    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 64M

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

# ========================================
# NETWORKS
# ========================================
networks:
  chatwoot_network:
    driver: overlay
    attachable: true

# ========================================
# VOLUMES
# ========================================
volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  chatwoot_storage:
    driver: local
  chatwoot_public:
    driver: local
